#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                                 \
    debug_output                 off            \
    mouse_follows_focus          off            \
    focus_follows_mouse          autoraise      \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                float          \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  8              \
    bottom_padding               8              \
    left_padding                 8              \
    right_padding                8              \
    window_gap                   8              \
    layout                       bsp            

# managed windows
# yabai -m rule --add app="^(Code)$" space=2

# unmanaged windows
yabai -m rule --add app="^(Finder|Calculator|Software Update|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Activity Monitor)$" manage=off

# borders
borders active_color=0xff88ccff inactive_color=0x00ffffff width=6.0 &

echo "yabai configuration loaded.."

