#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config debug_output on
yabai -m config focus_follows_mouse autoraise
yabai -m config window_placement second_child
yabai -m config window_shadow off
yabai -m config window_opacity off
yabai -m config split_ratio 0.50
yabai -m config auto_balance on

yabai -m config layout bsp
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# managed windows
yabai -m rule --add app="^(Code)$" space=2

# unmanaged windows
yabai -m rule --add app="^(Finder|Calculator|Software Update|VLC|System Preferences|System Information|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Activity Monitor)$" manage=off

# borders
borders active_color=0xff88ccff inactive_color=0x00ffffff width=6.0 &

echo "yabai configuration loaded.."

